# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addroom.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QDesktopWidget, QMessageBox
from utils.managedatabase import insertRoomItem, getRoomNameList, getFirebaseUrl, updateRoomList, deleteRoom


class CreateRoomWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedSize(439, 237)
        self.center()
        self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        self.tabWidget = QtWidgets.QTabWidget(self)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 421, 191))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 1, 411, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.onAddRoomClick)
        self.verticalLayout.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 411, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.activated.connect(self.onComboBoxChange)
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.onEditButtonClick)
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.onDeleteRoom)
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.retranslateUi(self)
        self.tabWidget.setCurrentIndex(0)
        self.show()
        self.updateEditItems()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Manage Rooms"))
        self.label.setText(_translate("MainWindow", "Room Name"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter room name here"))
        self.label_2.setText(_translate("MainWindow", "firebase.io URL"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter firbase.io URL"))
        self.pushButton.setText(_translate("MainWindow", "Add Room"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Add Room"))
        self.label_4.setText(_translate("MainWindow", "Choose room name:"))
        self.label_3.setText(_translate("MainWindow", "firebase.io URL"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter firebase.io URL"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit Room"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete Room"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Edit / Delete Room"))


    def onAddRoomClick(self):
        if self.lineEdit.text() == "" or self.lineEdit_2.text() == "":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Please enter room name and firebase url")
            msg.setWindowTitle("Add room")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
            return True
        else:
            a = insertRoomItem(self.lineEdit.text(),self.lineEdit_2.text())
            if a == 0:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Room added sucessfully")
                msg.setWindowTitle("Add room")
                msg.setStandardButtons(QMessageBox.Ok)
                msg.exec_()
                return True
            else:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Room already exists")
                msg.setWindowTitle("Add room")
                msg.setStandardButtons(QMessageBox.Ok)
                msg.exec_()


    def updateEditItems(self):
        a = getRoomNameList()[2]
        if len(a) != 0:
            for i in a:
                self.comboBox.addItem(i[0])
        b = getFirebaseUrl(self.comboBox.currentText())
        self.lineEdit_3.setText(b[2][0][0])

    def onComboBoxChange(self):
        b = getFirebaseUrl(self.comboBox.currentText())
        self.lineEdit_3.setText(b[2][0][0])


    def onEditButtonClick(self):
        try:
            updateRoomList(self.comboBox.currentText(),self.lineEdit_3.text())
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Room updated sucessfully")
            msg.setWindowTitle("Update room")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        except Exception as e:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Unable to update room")
            msg.setWindowTitle("Update room")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()


    def onDeleteRoom(self):
        try:
            deleteRoom(self.comboBox.currentText())
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Room deleted sucessfully")
            msg.setWindowTitle("Delete room")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        except Exception as e:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Unable to delete room")
            msg.setWindowTitle("Delete room")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()

    def center(self):
        qr = self.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())